# Configuration du serveur frontal (frontend)
frontend_ip: "51.158.167.76"
# Configuration du serveur backend (base de données)
backend_ip: "51.158.191.32"
# Domaine pour le site WordPress
domain: "apache.51.158.167.76.nip.io"

# Configuration de la base de données
db_name: "wordpress"
db_user: "wp_user"
db_password: "super_secure_password"
db_root_password: "root_super_secure_password"

# Configuration de l'administrateur WordPress
wp_admin_user: "admin"
wp_admin_password: "admin_secure_password"
wp_admin_email: "goffinet@goffinet.eu"

# Configuration de WordPress
wp_theme: "twentynineteen"
wp_language: "fr_FR"

# Chemin de la clé SSH pour les connexions
ssh_key_path: "/home/admsys/sshkey"

# Serveur web à utiliser (apache ou nginx)
web_server: "apache"

# Fichier de log
logfile: "deploy_wordpress.log"
